### ISSUE TITLE
Remove "where the organization is doing accessibility well"

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#100]
https://w3c.github.io/maturity-model/#About-maturity-model

I'm not sure what is meant with "where the organization is doing accessibility well"

We might change the sentence by just removing this, or rephrase...

(also add an 's' to 'provide', and change 'an' to 'the')

Change:

> The results of a maturity modeling assessment provide a holistic picture of an organization’s accessibility initiatives; where the organization is doing accessibility well and where improvements can be made to remove barriers.

To:
> The results of a maturity modeling assessment provide a holistic picture of the organization’s accessibility initiatives and where improvements can be made to remove barriers.

Or to:
> The results of a maturity modeling assessment provide a holistic picture of the organization’s accessibility initiatives; what is already going (done?) well, and where improvements can be made to remove barriers.

**Comment by Helixopp** [comment]
A new draft has been published. If you still have editorial recommendations please open a new issue.
