### ISSUE TITLE
What do we mean with 'aspects'? Used in two ways i.c.w. 'dimensions'

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#101]
The word 'aspects' is used as a synonym for dimension, and as sub-parts of a dimension.
I know/used it with the DAMM as a specific term, but here it seems we need to choose one version, or get rid of it at all.

https://w3c.github.io/maturity-model/#WCAG-maturity-model-audience

In the following sentence the dimension contains particular 'aspects'

> 1.2 Audience for the W3C Accessibility Maturity Model
> 
> The primary audience for this maturity model is:
> ...
> Other levels of management responsible for **particular aspects of the maturity of the defined dimensions**

https://w3c.github.io/maturity-model/#maturity-model-structure

In the following sentence 'aspects' is used as a synonym for 'dimension'

> 2. Maturity Model Structure
> The W3C Accessibility Maturity Model is organized around seven important aspects, or [dimensions](https://w3c.github.io/maturity-model/#dfn-dimension), of an [organization](https://w3c.github.io/maturity-model/#dfn-organization) where accessibility maturity can improve conformance with accessibility standards and regulations.

**Comment by clapierre** [comment]
@Helixopp will report changes here for each instance "aspect" is used in the document then @clapierre will change them in the document itself.

**Comment by Helixopp** [comment]
2. Maturity Model Structure
The Accessibility Maturity Model is organized around seven important aspects, or dimensions, of an organization where accessibility maturity can improve conformance with accessibility standards and regulations.

Change to:

The Accessibility Maturity Model is organized around seven essential dimensions of an organization where accessibility maturity can improve conformance with accessibility standards and regulations.

3.7 Culture
Organizational culture consists of shared beliefs, values, policies, and processes established by leaders that ultimately shape employee perceptions, behaviors, and understanding. To demonstrate cultural maturity in accessibility, all aspects of the organization’s operation, processes, and skills should include considerations for disability
inclusion. Every member of the organization should understand and be sensitive to the importance of ICT accessibility, including their personal role and responsibilities in meeting the organization’s accessibility goals. Accessibility should be an integral part of diversity and inclusion within the organization with clear recognition of the
benefits of disability inclusion and the impact of ICT accessibility on people with disabilities to facilitate access to jobs, services, and other aspects of life.

Change to:

3.7 Culture
Organizational culture consists of shared beliefs, values, policies, and processes established by leaders that ultimately shape employee perceptions, behaviors, and understanding. To demonstrate cultural maturity in accessibility, all aspects of the organization’s operation, processes, and skills should include considerations for disability inclusion. Every member of the organization should understand and be sensitive to the importance of ICT accessibility, including their personal role and responsibilities in meeting the organization’s accessibility goals. Accessibility should be an integral part of diversity and inclusion within the organization, with clear recognition of the benefits of disability inclusion and the impact of ICT accessibility on people with disabilities to facilitate access to jobs, services, and other aspects of life.

1.2 Audience for the Accessibility Maturity Model
This document is intended to guide and evaluate the levels of organizational accessibility maturity that encompasses a public or private sector organization at any scale.
The primary audience for this maturity model is:
Executive levels of an organization’s leadership
Other levels of management responsible for particular aspects of the maturity of the defined dimensions
Policy and business process subject matter experts responsible for putting plans, actions, metrics, and governance in place.

Change to:

1.2 Audience for the Accessibility Maturity Model
This document is intended to guide and evaluate the levels of organizational accessibility maturity that encompasses a public or private sector organization at any scale.
The primary audience for this maturity model is:
Executive levels of an organization’s leadership
Other levels of management responsible for accessibility maturity
Policy and business process subject matter experts responsible for putting plans, actions, metrics, and governance in place.
