### ISSUE TITLE
Proof Point definition to be adjusted to fit under an Outcome

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#102]
https://w3c.github.io/maturity-model/#key-terms

The proof point is directly linked to the dimension, while it should be linked to an outcome, another proof point might be used for the same outcome if it fits...

Change:
> proof point
> Written or tangible evidence specific to each [dimension](https://w3c.github.io/maturity-model/#dfn-dimension) that can be used to measure the maturity for that specific dimension.

To:
> proof point
> Written or tangible evidence specific **to an outcome of** a [dimension](https://w3c.github.io/maturity-model/#dfn-dimension) that can be used to measure the maturity for that specific **outcome**.

**Comment by Helixopp** [comment]
@swinehartganderson please apply to usability doc

We propose the following language change:

Written or tangible (written/tangible verbiage addressed in issue 104, incorporate that change as well)evidence specific to outcomes defined for each stage of a dimension.  This evidence is used to assess the maturity for that dimension.

**Comment by Helixopp** [comment]
The document has been updated with the following definition:

Each dimensional outcome has a range of suggested proof points, which includes any evidence or necessary measures that can be used to determine the maturity of each dimension. Progress towards achieving maturity is attained by creating the proof points described for each dimension.

Proof points are evidence-based, organizational deliverables which indicate the maturity stage.
Proof points are specific to the dimension being focused on. For example, if only procurement maturity is being measured, only procurement proof points should be evaluated.
For some dimensions, proof points are further organized by category.
Proof points can be partially completed at the Launch and Integrate stages, but must be fully completed for the optimize stage.
For example, if a dimension requires a plan to identify ICT accessibility related skill levels and gaps, then the corresponding proof point would be a document containing the evaluation of ICT accessibility related skill levels and gaps.
