### ISSUE TITLE
Where are the "Outcomes" in the Maturity Model Structure?

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#103]
https://w3c.github.io/maturity-model/#maturity-model-structure

The structure is mentioned as:

> Each dimension has two sub-sections:
> - Proof points...
> - Maturity stages...

But proof points are optional / not required, it's the Outcomes that count, and if you have another proof point for that Outcome, that is fine, as long as the Outcome is fulfilled...

So, it should be 

> Each dimension has two sub-sections:
> -  Outcomes (with possible related proof points...)
> - Maturity stages (with specific Outcomes)

We can start with showing proof points if we wish, but the dimensions themselves do not have two sub-sections "proof points' and "maturity Stages', Our document may have it setup that way, but it is confusing to say a dimension has the two sub-sections ... PP and MS

**Comment by Helixopp** [comment]
will be addressed in upcoming editors draft

**Comment by Helixopp** [comment]
We believe the latest working draft addresses your concerns in this issue. If they still persist please reopen the issue or file a new one
