### ISSUE TITLE
Proof points = Written or tangible evidence, according to definition, not an 'or' / 'other' part / sub-section

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#104]
https://w3c.github.io/maturity-model/#maturity-model-structure

The 'or' makes it different from the proof point, while it is 'the other one specified, not being "written evidence"'

See also the definition:

> proof point
> Written or tangible evidence specific to each [dimension](https://w3c.github.io/maturity-model/#dfn-dimension) that can be used to measure the maturity for that specific dimension.

Change:
> Proof points, or tangible evidence, that can be used ....

To:
> Proof points that can be used ....

Or to:
> Proof points (written or tangible evidence) that can be used ....

**Comment by Helixopp** [comment]
Will be addressed in upcoming editors draft
