### ISSUE TITLE
Definition Knowledge and Skills needs some adjustment

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#105]
https://w3c.github.io/maturity-model/#description-dimensions

"Ongoing" might not be required all the time, and "to fill gaps for accessibility operations." seems like an add-on for accessibility.
Have a proposal to cover more what it stands for.

Change:
> Knowledge and Skills: Ongoing education, and outsourcing practices to fill gaps for accessibility operations.

To: 
> Knowledge and Skills: Assessing, educational efforts, and outsourcing practices to fill gaps in understanding and applying accessibility practices.

**Comment by Helixopp** [comment]
A new draft has been published. If you still have editorial recommendations please open a new issue.
