### ISSUE TITLE
Support definition needs a tweak, "internal employees" are not covering all employees...

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#106]
https://w3c.github.io/maturity-model/#description-dimensions

When we talk about 'internals' or 'internal employees', we means the employees with permanent contracts.
Temporary workers or external workers via other companies do not fall under this definition, but still deserve the same treatment.

So add both or delete 'internal'

Change:
> Support: Accessibility assistance provided to internal employees and external [customers](https://w3c.github.io/maturity-model/#dfn-customer) with disabilities.

To:
> Support: Accessibility assistance provided to internal / external employees and external [customers](https://w3c.github.io/maturity-model/#dfn-customer) with disabilities.

Or to:
> Support: Accessibility assistance provided to employees and external [customers](https://w3c.github.io/maturity-model/#dfn-customer) with disabilities.

**Comment by Helixopp** [comment]
A new draft has been published. If you still have editorial recommendations please open a new issue.
