### ISSUE TITLE
Definition of  "Full maturity" needs to be adjusted, as there is no need to optimize anymore by then

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#107]
https://w3c.github.io/maturity-model/#knowledge-ratings-for-evaluation

Definition at K & S for "Optimize" is: (and also for other dimensions the word 'Full maturity' is used...)

> Definition: Full [organization](https://w3c.github.io/maturity-model/#dfn-organization) ICT accessibility maturity. Organization-wide, role-based expertise in accessibility and disability inclusion is well-defined, evaluated, remediated, and continuously enhanced. Accessibility knowledge and skills are consistently implemented across the organization.

When **"Full maturity"** is reached, it seems like no need anymore for optimizing anything.
This should be changed to a state where you've reached Level 3 but there's always room for improvement.

**Comment by Helixopp** [comment]
A maturity Model is a continuum, there is no end point. The Task Force has decided to keep the term optimize, as it suggests an ongoing effort without an end point.
