### ISSUE TITLE
Definitions for Maturity Stages too long

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#108]
My 2 cent for "Personnel", "Knowledge and Skills" and some separate definitions for the Maturity Stages is that they are too long.

1 concise sentence should be enough, as also other definitions already show.
We need to go over them and see if can can shorten the longer ones to make them stronger and easier.

**Comment by jake-abma** [comment]
Basically I would like to suggest using the ones we started with as a basis for all:

(or possibly even better, use the same for all? Making it so much more easy / simplifying it)

0. There is no awareness and recognition of need for the Proof Point
1. The Proof Point is recognized as a need organization-wide, where planning is initiated and activities present, but not well organized
2. Processes and procedures in place but inconsistently implemented across the organization
3. The Proof Point is fully implemented based on assessments consistently evaluated across the organization

**Comment by jake-abma** [comment]
UPDATE: would suggest to change 'and' for 'or' as there may be awareness BUT not recognized as a need (on purpose or not, doesn't matter...)

1. There is no awareness or recognition of need for the Proof Point
2. Recognized as a need organization-wide, where planning is initiated and activities present, but not well organized
3. Processes and procedures in place but inconsistently implemented across the organization
4. The Outcomes for Stage 3 are all implemented based on assessments and consistently evaluated across the organization

(Ps. This also makes place / room for an update / simplification of the table...! see:
NEWEST Simplified OUTCOME K&S Evidence: 
https://docs.google.com/spreadsheets/d/1fzPlHjHIaSQn9GvpJd86SDpV49U8Beg_iXj6K5aeyGg/edit#gid=1976182056 )

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
