### ISSUE TITLE
Starting with the definition for each Dimension under 3. Accessibility Maturity Per Dimension

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#109]
https://w3c.github.io/maturity-model/#description-dimensions

We have definition for each dimension at 2.1, it would be good to see them back start with them where we explain / go in-depth with the dimensions separately at **3. Accessibility Maturity Per Dimension**

> 2.1 Dimensions
> The seven [dimensions](https://w3c.github.io/maturity-model/#dfn-dimension) of organizational accessibility maturity are:
> 
> - Communications: Information as it relates to an [organization](https://w3c.github.io/maturity-model/#dfn-organization)’s accessibility, as well as accessibility of all internal/external communications.
> - Knowledge and Skills: Ongoing education, and outsourcing practices to fill gaps for accessibility operations.
> - Support: Accessibility assistance provided to internal employees and external [customers](https://w3c.github.io/maturity-model/#dfn-customer) with disabilities.
> - ICT (Information and Communication Technology) Development Life Cycle: Incorporation of web, software and hardware accessibility considerations in development processes - from idea conception, to design, development, testing, ACR production, user research, maintenance and obsolescence.
> - Personnel: Job descriptions, recruiting, disability-related employee resource groups necessary to provide lived-experience to accessibility efforts.
> - Procurement: A strategic process that concentrates on finding and acquiring accessible products required by an organization. Activities may include: sourcing, negotiation, and selecting goods and services.
> - Culture: The attitudes, sensitivity, and behaviors around accessibility, including internal interaction, perception, and decision-making.

**Comment by Helixopp** [comment]
We believe the latest working draft addresses your concerns in this issue. If they still persist please reopen the issue or file a new one
