### ISSUE TITLE
Relationship Outcomes for stages and Proof Points not clear

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#110]
https://w3c.github.io/maturity-model

When starting to add / use the Outcomes to be achieved for a stage, it not clear what their relationship is with which Proof Point.
They are both separate lists, Proof Points also categorized (which outcomes also kind of should do already) making it even harder, and it seems they are introduced separately where the 'connection' is lost.

Basically you'll expect a structure with outcomes and proof points belonging to that specific Outcome. A clear Hierarchy.
Now it's up to the 'user' to try to figure out what belongs where and which one to use at which stage.
I can imagine this is way too hard for people to understand clearly and apply is a fast way.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
