### ISSUE TITLE
Outcomes not consistently written and not covering the intent of the Stage

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#111]
https://w3c.github.io/maturity-model/#development-lifecycle-ratings-for-evaluation

This is just an example for ICT Dev Life Cycle, but not limited to this one specifically, just serving as an example...!

> 3.2.2 Ratings for Evaluation
> 
> Inactive: Oucomes => If ACRs are required, they are not being produced.

At the inactive stage, the question 'If ACRs are required' (, they are not being produced.) is not relevant or the Outcome to be judged for this Level.

Same for the Launch Stage:

> Launch: Outcomes => Accessibility efforts may be limited in scope to new products, applications, and websites.

**'may be limited in scope'** and then **'to new products'** I guess this is not the Outcome to be evaluated to judge the Stage level.

Why 'limited in scope' and why specifically for 'new products' and nothing else as an Outcome?

These are just 2 examples where I have a hard time working out a spreadsheet with Stages/Levels for each dimension and trying to figure out how the proof points relate to the levels.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
