### ISSUE TITLE
Change Proof Point 2 for 3.2.1.1 Assessing Current Skills to Identify and Address Gaps

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#113]
https://w3c.github.io/maturity-model/#assess-knowledge-and-skills

For the following proof point it does not have to be "internal" and also " database(s)" are not required / the only solution, so suggesting to get rid of them both.

Change:
> Internal database(s) to track employee training for ICT accessibility skills

To:
> Tracking of employee training for ICT accessibility skills

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
