### ISSUE TITLE
Delete "Keeping skills up-to-date with current requirements" in 3.2.1.1 Assessing Current Skills to Identify and Address Gaps

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#115]
https://w3c.github.io/maturity-model/#assess-knowledge-and-skills

The Proof Point "Keeping skills up-to-date with current requirements" doesn't fit the Outcome "Assessing Current Skills to Identify and Address Gaps"

Keeping skills up-to-date is not assessing the skills...

Basically this one is already covered by the other Proof Points, so deleting is the best option.

**Comment by jake-abma** [comment]
Basically this one belongs to the next Outcome: "3.2.1.2 Building and Maintaining Organizational Capacity" but there are already a Proof Point there "Implementation of role based training plans and curriculums" covering this one... so still "delete"

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
