### ISSUE TITLE
Do we need to mention "employee and management" for 3.2.1.1

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#116]
https://w3c.github.io/maturity-model/#assess-knowledge-and-skills
3.2.1.1 Assessing Current Skills to Identify and Address Gaps

Do we really need to mention "employee and management" in a Proof Point?
We can repeat/copy this multiple times but mentioning that the MM is for the whole organization somewhere is enough (?!) or make a stronger statement for ALL Proof Points somewhere (?!)

If we keep it move to last part of sentence...

Delete or Change (employee and management):
> Accessibility criteria integration into individual (employee and management) performance measurements

To:
> Accessibility criteria integration into individual performance measurements
> Accessibility criteria integration into individual performance measurements (employee and management)

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
