### ISSUE TITLE
Type "role based" to "role-based" 3.2.1.2

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#117]
https://w3c.github.io/maturity-model/#building-organizational-capacity

Change:
>Implementation of role based training plans and curriculums

To:
> Implementation of role-based training plans and curriculums

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
