### ISSUE TITLE
Knowledge and Skills - Proof Point Updates

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#118]
I've updated the Proof Points for Knowledge and Skills

Used the "old ones" the "renewed ones" and did a DIFF + updates...

"renewed ones": https://w3c.github.io/maturity-model/#knowledge-and-skills-proof-points

DIFF file:
[Knowledge and Skills - A11Y Planning Q3 - 2022.docx](https://github.com/w3c/maturity-model/files/9393259/Knowledge.and.Skills.-.A11Y.Planning.Q3.-.2022.docx)

Example of adjusted Spreadsheet for Rating the Maturity can be found at:
https://docs.google.com/spreadsheets/d/1fzPlHjHIaSQn9GvpJd86SDpV49U8Beg_iXj6K5aeyGg/edit#gid=1436692944 

**!!! NEW VERSION and Simplified Spreadsheet / Table for the Dimensions !!!**
https://docs.google.com/spreadsheets/d/1sbfh2Kone3Poe9CGw-llOriBPK3GnGDj3YY2GmDZH80/edit#gid=600224467

BELOW THE NEW PROPOSAL FOR PROOF POINTS:
-------------------------------------------------------------------------

### Assessing Current Skills to Identify and Address Gaps

- Organizational surveys that identify current skill levels and gaps
- Tracking employee training for ICT accessibility skills
- Certification or competency reviews and programs
- Accessibility criteria integration into individual performance measurements  (employee and management) 

### Building and Maintaining Organizational Capacity

- Awareness campaigns (also pertinent to the Cultural dimension)
- Accessibility training when onboarding all new employees
- Implementation of role-based training plans and curriculums
- Organizing and attending digital accessibility events
- Learning management, tracking, and auditing systems
- Accessibility requirements included in position descriptions
- Subject matter experts (SMEs) positioned within the organization to provide training and support
- Procured external resources for training and development
- Procured external resources for development (add this one?)

BELOW THE TEX FROM THE WORD DOC WITHOUT STRIKE THROUGHS:
-------------------------------------------------------------------------

Knowledge and Skills

Knowledge and Skills DIFF

Assessing Current Skills to Identify and Address Gaps

(OLD: Conveys Insights of Knowledge and Skills for deciding approach)
- Assessments of K&S gaps
- Investigation of educational efforts
- Gain Insights on working experience and certification
- Inspection of individual performace plans / job requirements
- Investigation of responsibilities for job description

NEW PROOF POINTS
-	Organizational surveys that identify current skill levels and gaps
-	Tracking employee training for ICT accessibility skills
-	Certification or competency reviews and programs
-	Keeping skills up-to-date with current requirements
-	Accessibility criteria integration into individual performance measurements  (employee and management) 

Building and Maintaining Organizational Capacity
(OLD: Offers Training to improve competence)
(OLD: Hires External Knowledge and Skills for conformance)

- Basic awareness training for all staff
- Refering to courses and workshops
- Onboarding for new employees
- Setup of training program
- Organizing and attendance of events
- Having an Empathy Lab
- Direct expert hotline

- Has external hire in-house
- Has external support line
- Audits done externally
- Development done externally

NEW PROOF POINTS
-	Awareness campaigns (also pertinent to the Cultural dimension)
-	Accessibility training when onboarding all new employees
-	Implementation of role-based training plans and curriculums
-	Incorporation of digital accessibility training curricula into organization (DOUBLE, see previous Proof Point)
-	Organizing or attending digital accessibility events to increase awareness and knowledge
-	Learning management, tracking, and auditing systems
-	Accessibility requirements included in position descriptions
-	Subject matter experts (SMEs) positioned within the organization to provide training and support
-	Procured external resources for training and development , as needed

Dimension Integration: Training and learning programs should be integrated into proof points for each dimension

(OLD: Offers Documentation and Resources for self learning)

- Internal systems contain resources
- Referring present to external resources
- Documentation for implementations
- Media Channel for accessibility related questions
- Informing print material and posters present

NEW PROOF POINTS
- Training and learning programs should be integrated into proof points for each dimension

This is not a Proof Point but more of a note…!

**Comment by Helixopp** [comment]
Thank you, for your comment. We have taken it into consideration, along with other feedback from the public, and significantly revised the document. We believe that we have addressed your concern. If it still persists, please open a new issue, and provide any supporting documentation, you would like
