### ISSUE TITLE
Delete "3.2.1.3 Dimension Integration" from Knowledge and Skills

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#119]
https://w3c.github.io/maturity-model/#dimension-integration

3.2.1.3 is not an Outcome or even a Proof Point, it's more a Note that "Training and learning programs should be integrated into [proof points](https://w3c.github.io/maturity-model/#dfn-proof-point) for each dimension"

> 3.2.1.3 Dimension Integration
> - Training and learning programs should be integrated into [proof points](https://w3c.github.io/maturity-model/#dfn-proof-point) for each dimension

So I suggest to remove it as a Proof Point and add a Note with this text.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
