### ISSUE TITLE
Step 1: Rating / Stages Update for Knowledge and Skills for Definitions

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#120]
https://w3c.github.io/maturity-model/#knowledge-ratings-for-evaluation

Rating - Knowledge and Skills

**SUMMARY:**
**Mixing and Matching (text of) Proof Points and (text of) Outcomes in definitions for Ratings/Levels gets us into trouble as it just conflicts the Framework itself and limits Proof Points and Outcomes to specific Levels/Ratings. This contradicts a seamless system where you can mature in Outcomes and Proof Points going from Inactive, to Launch, to Integrate, to Optimize**

Also having standard definitions for the Levels, consistent across all Dimensions, makes the overall Rating/Levels easy to understand and clear to work with. **For this reason I suggest to use them for ALL dimension consistently.**

OUTCOMES IN DEFINITION:

The Definitions should NOT contain Outcomes or Outcome text, that is for the Outcome itself. Outcome may be optional depending on the organization and so should the outcome text be.

Also placing Outcome text for a specific Rating/Level only works counter productive as it suggests there might  be no starting point, no grow possible, or that all work is done at Level 2, so no need to try to get to Level 3.

EXAMPLE: why is “Integration of process to assess and increase accessibility knowledge and skills is in progress” only at Level 2? Should start in Level 1 and should go all the way to Level 3.

PROOF POINTS IN DEFINITION:

The Definitions should NOT contain Proof Point(s) or Proof Point text, that is for the Proof Point itself. Proof Points are optional and so should the proof point text be.

EXAMPLE: why is “…with required role-based accessibility expertise defined” while it is a Proof Point for an Outcome.

Rating “Maturity stages and Criteria” DIFF

Inactive

Old Definition:
No efforts to develop W3C accessibility knowledge or skills.

Suggested Definition:
There is no awareness and recognition of need for the Proof Point

Launch

Old Definition:
Recognized need for organization-wide accessibility and disability inclusion, as well as accessibility expertise. Planning initiated, but activities not well organized.

Suggested Definition:
Recognized as a need organization-wide, where planning is initiated and activities present, but not well organized

Integrate

Old Definition:
Workforce ICT accessibility skills and training roadmap in place with an overall organizational approach to disability inclusion with required role-based accessibility expertise defined. Integration of process to assess and increase accessibility knowledge and skills is in progress, but not consistently implemented across the organization.

Suggested Definition:
Processes and procedures in place but inconsistently implemented and evaluated across the organization

Optimize

Old Definition:
Full organization ICT accessibility maturity. Organization-wide, role-based expertise in accessibility and disability inclusion is well-defined, evaluated, remediated, and continuously enhanced. Accessibility knowledge and skills are consistently implemented across the organization.

Suggested Definition:
The Proof Point is fully implemented based on assessments and consistently evaluated across the organization

Attached Word Document for the Changes:
[Rating - Knowledge and Skills - A11Y Planning Q3 - 2022.docx](https://github.com/w3c/maturity-model/files/9393716/Rating.-.Knowledge.and.Skills.-.A11Y.Planning.Q3.-.2022.docx)

**Comment by jake-abma** [comment]
**!!! NEW VERSION and Simplified Spreadsheet / Table for the Dimensions !!!**
https://docs.google.com/spreadsheets/d/1sbfh2Kone3Poe9CGw-llOriBPK3GnGDj3YY2GmDZH80/edit#gid=600224467

**Comment by Helixopp** [comment]
We believe the latest working draft addresses your concerns in this issue. If they still persist please reopen the issue or file a new one
