### ISSUE TITLE
Step 2: Rating / Stages Update for Knowledge and Skills for Outcomes

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#121]
https://w3c.github.io/maturity-model/#knowledge-ratings-for-evaluation

Outcomes - Knowledge and Skills

**SUMMARY:**
Basically the Outcomes are / or should be the ‘categorization’ of Proof Points.
The Proof Points ‘proof’ the desired outcome(s) to be achieved for each Dimension.

Mixing and Matching (text of) Proof Points and (text of) Definitions in Outcomes for Ratings/Levels gets us into trouble as it just conflicts the Framework itself and limits Proof Points and Outcomes to specific Levels/Ratings. This contradicts a seamless system where you can mature in Outcomes and Proof Points.

For Knowledge and Skills we already have defined 2 Outcomes, e.g.;

1.	Assessing Current Skills to Identify and Address Gaps
2.	Building and Maintaining Organizational Capacity

If this is complete, or needs to be broken up is another question, but for now this is what we work with… see 3.2.1.1 and 3.2.1.2

**MY CONCLUSION**
Basically get rid of ALL Outcomes in ALL tables as we now have two systems in place contradicting each other, where the current situation of having Specific Defined Outcomes at a certain Level makes a Framework very restrictive an even unusable for lots of organizations (the organization where I work is already an example where we do not agree with required Outcomes) to achieve a certain Level of maturity.
What we do need to do is check all Rating/Level Outcomes and see if they fit the Outcome/Proof Point structure setup for gaps. So merge them if needed into 1 structure/system, not 2 at the same time conflicting each other.

**DEFINITIONS IN OUTCOMES:**

The Outcomes should NOT contain Definitions or Definition text, that is for the Definition itself. Outcomes should be consistent for a Dimension and may depends on the organization and so should the Outcome text be.

Also placing specific Outcome text for a specific Rating/Level only works counter productive as it suggests there might  be no starting point, no grow possible, or that if all work is done at Level 2, there’s no need to try to get to Level 3.

**PROOF POINTS IN OUTCOMES:**

The Outcomes should NOT contain Proof Point(s) or Proof Point text, that is for the Proof Point itself. Proof Points are optional and so should the proof point text be.

EXAMPLE: why is “…role based training plans” in “Launch” while it already is a Proof Point for an Outcome, see “3.2.1.2 Implementation of role based training plans and curriculums”

**OUTCOMES AND ORGANIZATION SPECIFIC SOLUTIONS**

Outcomes should be a statement for fulfilling a desired ‘outcome’ for a Dimension, not specific solutions/proof points/ or organization specific features to achieve the Outcome.

**EXAMPLES VERY SPECIFIC BUT NOT PER SE NEEDED FOR THE LEVEL OF MATURITY:**
-	“Requirements defined for 3rd party learning”
-	that includes accessibility objectives for:
o	Knowledge and skills assessments
o	Available training for their role
o	Current information on new technologies, platforms, and tools
-	Workforce inclusion training incorporates accessibility for persons with disabilities.
o	Certification programs are available

**CONCLUSION:**
1.	Lots of defined Outcomes do not match the Proof Points above, they should have a clear relationship.
2.	The Outcomes are very specific, and not usable over multiple Ratings/Levels, making it a bit weird/hard to ‘proceed’ / ‘mature’
3.	Outcomes are a mix of Rating Definitions, Proof Points, and even possible organization specific solutions not needed for the LEvel
4.	Outcomes prescribe situations / requirements to granular where we should leave that to the organization itself which proof point is what way to use. It’s their promise, not our requirement.

**Comment by Helixopp** [comment]
We believe the latest working draft addresses your concerns in this issue. If they still persist please reopen the issue or file a new one
