### ISSUE TITLE
Step 3: Outcomes from Rating to Outcome/Proof Points DIFF / MAPPING - Knowledge and Skills

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#122]
https://w3c.github.io/maturity-model/#knowledge-ratings-for-evaluation

Been through all Outcomes in the Rating Level section to see if it is an Outcome, or a Proof Point, or just part of the definition already, or a combination of all of them.

**MY CONCLUSION: DELETE ALL OUTCOMES IN RATING SECTION**
My conclusion is that all Outcomes are redundant / not needed, except for / maybe add: “communication to Project Management”. All others can be deleted as they clutter the Framework not adding useful extra info or structure, instead making it more confusing.“

Word document can be found at:
[Outcomes to Proof Points - Knowledge and Skills - A11Y Planning Q3 - 2022.docx](https://github.com/w3c/maturity-model/files/9394633/Outcomes.to.Proof.Points.-.Knowledge.and.Skills.-.A11Y.Planning.Q3.-.2022.docx)

------------------------------------------------------------------
ALL INFORMATION FROM THE TEXT FROM THE WORD DOC BELOW HERE:
------------------------------------------------------------------

Outcomes from Rating to Outcome/Proof Points DIFF / MAPPING - Knowledge and Skills

SUMMARY:
Going through all Outcomes in the Rating tables and see if already covered OR the Outcome/Proof Point selection need to be updated so we do not loose any information.
Current updated set of Outcomes and Proof Points:
https://github.com/w3c/maturity-model/issues/118 

Assessing Current Skills to Identify and Address Gaps
•	Organizational surveys that identify current skill levels and gaps
•	Tracking employee training for ICT accessibility skills
•	Certification or competency reviews and programs
•	Accessibility criteria integration into individual performance measurements (employee and management)
Building and Maintaining Organizational Capacity
•	Awareness campaigns (also pertinent to the Cultural dimension)
•	Accessibility training when onboarding all new employees
•	Implementation of role-based training plans and curriculums
•	Organizing or attending digital accessibility events
•	Learning management, tracking, and auditing systems
•	Accessibility requirements included in position descriptions
•	Subject matter experts (SMEs) positioned within the organization to provide training and support
•	Procured external resources for training and development

To be Judged / Present Outcomes at Rating

Red: not needed / already covered
Green: gap not filled, new Outcome or Proof Point added

Please ask for explanation clearance if you cannot see red/green or colors at all.

CONCLUSION: all Outcomes are redundant / not need, except for / maybe add: “communication to Project Management”. All others can be deleted as they clutter the Framework not adding useful extra info or structure, instead making it more confusing.“

Inactive Outcomes
•	None; no accessibility effort at all around developing accessible technology, disability inclusion, or improving accessibility knowledge and skills.
o	No need to do anything, as there are no outcomes/proof points here

Launch Outcomes
•	Skill areas identified, plans for organization wide surveys to identify gaps initiated, but not implemented.
o	Skill areas identified => is part of the task for proof point: “Organizational surveys that identify current skill levels and gaps“, not an Outcome by itself
o	“plans for organization…” is already part of the Level definition: “planning is initiated” so redundant to mention
o	Same for “but not implemented”, and basically going against “activities present, but not well organized”
•	Mostly Ad hoc training (professional development is not required or monitored.)
o	“Accessibility and role-based Training” is a Proof Point, “Ad hoc’ is a property of “activities present, but not well organized”
•	Requirements defined for 3rd party learning tools and systems. Work initiated on role based training plans.
o	“Requirements defined for 3rd party” => that is for Procurement, not Knowledge and Skills
o	“Work initiated on role based…” is part of the definition and proof point already
•	Some training courses established.
o	is part of the definition and proof point already

Integrate Outcomes

•	Workforce skills and training roadmap that includes accessibility objectives for:
o	Knowledge and skills assessments
o	Available training for their role
o	Current information on new technologies, platforms, and tools
	“roadmap that includes” => seems like a Proof Point you can mature in… or it is a planning choice / activity up to the organization…?
	A combined Outcome? What is 2 are achived but not all / 3? And what if the 2 are already enough for maturity, too prescriptive…
	“Current information on new technologies, platforms, and tools” that is also too prescriptive and too broad, leave it up to organizations how to fill in a ‘promise’?!
•	Training is available to enhance knowledge and skills around ICT accessibility, and disability inclusion
o	This is applicable to Level 1, 2, and 3!!! So why here in this way?
•	Training metrics are established
o	Also here, this is applicable for at least Level 2, and 3, but probably you’ll start at Level 1
o	Already part of Proof Point: “Learning management, tracking, and auditing systems”?

Optimize Outcomes

•	Required and preferred knowledge and skills are consistently communicated to all personnel
o	Position descriptions
o	Hiring announcements
o	Project management
o	=> Accessibility requirements included in position descriptions is already a Proof Point
o	communication to Project Management might be a Proof Point ?!
•	Workforce is periodically evaluated to ensure knowledge and skills are current with the most up to date standards and accessibility practices.
o	That is already the definition of the Rating/Level 3
•	Periodic analysis used to identify gaps in knowledge as well as training materials.
o	That is already the definition of the Rating/Level 3
•	Annual training (conferences, events, online, etc.) is provided to maintain skills current with ICT accessibility requirements and industry best practices. Workforce inclusion training incorporates accessibility for persons with disabilities.
o	Already a Proof Point: “Organizing or attending digital accessibility events“
•	Certification programs are available
o	Already a Proof Point “Certification or competency reviews and programs“ and applicable for all Levels
•	Tracking systems in place and consistently used to maintain training inventory, measure skills, and track completion
o	Same here, part of Level 3 definition, but not limited to only level 3, you start at level 1, or 2 with the first approaches…

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
