### ISSUE TITLE
Delete "W3C" from "Inactive: Definition: No efforts to develop W3C accessibility knowledge or skills."

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#123]
https://w3c.github.io/maturity-model/#knowledge-ratings-for-evaluation

The word "W3C" needs to be deleted from the definition of "Inactive"

Change:
> Definition: No efforts to develop W3C accessibility knowledge or skills.

To:
> Definition: No efforts to develop accessibility knowledge or skills.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
