### ISSUE TITLE
Update DLC Spreadsheet - Step 1

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#125]
https://w3c.github.io/maturity-model/#ict-development-lifecycle

I've **Updated the spreadsheet for DLC, keeping all 'categories' and 'proof points'** as defined in https://w3c.github.io/maturity-model/#development-lifecycle-proof-points 

This is the first step towards a new proposal for DLC, as already done for Knowledge and Skills, Outcome based and completely re-evaluated...

Spreadsheet Update can be found at: (UPDATED OUTCOME ICT DLC Evidence - Jake)
https://docs.google.com/spreadsheets/d/1fzPlHjHIaSQn9GvpJd86SDpV49U8Beg_iXj6K5aeyGg/edit#gid=627214460 

Already started working on a NEW approach, this one can be found at: (NEWEST OUTCOME ICT DLC Evidence - Jake)
https://docs.google.com/spreadsheets/d/1fzPlHjHIaSQn9GvpJd86SDpV49U8Beg_iXj6K5aeyGg/edit#gid=1296637612 

(More info on the "NEWEST" version / approach will be added in other 'to be created' issues)

**Comment by jake-abma** [comment]
**!!! NEW VERSION and Simplified Spreadsheet / Table for the Dimensions !!!**
https://docs.google.com/spreadsheets/d/1sbfh2Kone3Poe9CGw-llOriBPK3GnGDj3YY2GmDZH80/edit#gid=600224467

**Comment by clapierre** [comment]
That spreadsheet has been updated and is now in excel spreadsheet. This should be now addressed.
