### ISSUE TITLE
Cleanup / adjust 3.4.2 Ratings for Evaluation ICT Development Lifecycle

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#127]
https://w3c.github.io/maturity-model/#development-lifecycle-ratings-for-evaluation 

As the proposed adjustment is to place Outcomes as the basis and Proof Points to be part of a specific Outcome, a double approach to also place Outcomes in this table is redundant and even confusing.

All Outcomes are applicable to all Levels / Ratings and the Proof Points need to be matured from 0 to 3, Inactive to Optimize.

So the proposed adjustment would be to have the table look like the following example OR just removed as they will be part of the spreadsheet.

---------------------------------

> Level 0 - Inactive
> Definition:
> There is no awareness and recognition of need for the Proof Point
> 
> Level 1 - Launch
> Definition:
> Recognized as a need organization-wide, where planning is initiated and activities present, but not well organized
> 
> Level 2 - Integrate
> Definition:
> Processes and procedures in place but inconsistently implemented and evaluated across the organization
> 
> Level 3 - Optimize
> Definition:
> The Proof Point is fully implemented based on assessments and consistently evaluated across the organization

---------------------------------

I've gone through all OLD Outcomes to see whether they fit the Outcome / Proof Point as mapped already.
This is what I've done with the information:

---------------------------------

Maturity stages	Criteria

> Inactive
> Definition: No accessibility effort at all around ICT development.
> 
> Outcomes:
> - If ACRs are required, they are not being produced.

I do not understand this one as the Outcome for Inactive, it certainly is not something we know at all in Europe as some kind of 'standard approach' Suggestion to just delete. I do have "customer-reported feedback" as a Proof Point

> Launch
> Definition: Some awareness and recognition of the need for accessible ICT development, inconsistently approached, decentralized.
> 
> Outcomes:
> - Accessibility efforts may be limited in scope to new products, applications, and websites.

 This is already what the Definition states but just slightly different in wording, delete is the suggestion

> Integrate
> Definition: Organizational effort and approach for improving accessibility in ICT development per role or discipline.
> 
> Outcomes:
> - Accessibility requirements are considered and practiced during ICT design, development, and testing, but are not consistently applied across the ICT portfolio.
> - Some attempt is made to remediate existing products, applications, and websites.

This is already what the Definition states but just slightly different in wording, delete is the suggestion

> Optimize
> Definition: Thought leader in Accessibility on ICT development with strong ICT development knowledge and skills, structural, standardized and reported approach.
> 
> Outcomes:
> - Design specifications include accessibility guidance, developers consistently create accessible User Interface (UI), both manual and automated accessibility testing is performed during development, and automated accessibility testing is incorporated into Continuous Integration/Continuous Delivery (CI/CD) build pipelines
> - Release management includes gates for accessibility quality.
> - Maintenance releases are re-inspected for accessibility.
> - ACRs are kept up to date and made available, as needed, for procurable ICT.
> - Research deliberately seeks out and evaluates input from users with disabilities.

These are all just Outcomes / Proof Points which start at Level 0, and also part of level 1 and 2, to be matured... Only mentioning at Level 3 is not how you can 'grow' and already part of the Definition itself... deleting justified.

I have seen no extra information not already covered in the suggested Proof Points / Outcomes, see: https://github.com/w3c/maturity-model/issues/122

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
