### ISSUE TITLE
NEW VERSION and Simplified Spreadsheet / Table for the Dimensions

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#128]
I've simplified the Spreadsheet / Table / Tabs for the Dimensions.

Basically just got rid of the first column, now you start with all Proof Points in 'inactive (red)' and need to mature to get them all into 'Optimize (green)'.

Two examples can be seen at:

[DELETED OLD SPREADSHEET LINKJS...]

**Comment by jake-abma** [comment]
On basis of the latest "Test Spreadsheet" the new Spreadsheet URL is at:

NEWEST Simplified OUTCOME K&S Evidence:
https://docs.google.com/spreadsheets/d/1sbfh2Kone3Poe9CGw-llOriBPK3GnGDj3YY2GmDZH80/edit#gid=1548563475

NEWEST Simplified OUTCOME ICT DLC Evidence - Jake:
https://docs.google.com/spreadsheets/d/1sbfh2Kone3Poe9CGw-llOriBPK3GnGDj3YY2GmDZH80/edit#gid=600224467

**Comment by clapierre** [comment]
This should be now addressed in the new excel spreadsheet.
