### ISSUE TITLE
Conflict in position Training Knowledge and Skills Vs. DLC

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#129]
https://w3c.github.io/maturity-model/#dimension-integration

As can be seen at 3.2.1.3 Dimension Integration, the choice was made to "Training and learning programs should be integrated into [proof points](https://w3c.github.io/maturity-model/#dfn-proof-point) for each dimension"

Now in "3.2.1.2 Building and Maintaining Organizational Capacity" there's a Proof Point:

> Implementation of role based training plans and curriculums

https://w3c.github.io/maturity-model/#building-organizational-capacity

And in ICT DLC there is:

> 3.4.1.5 ICT Development Training
> Accessibility in the ICT lifecycle training is in place to build and maintain relevant role-based skills in support of this dimension’s [proof points](https://w3c.github.io/maturity-model/#dfn-proof-point)
https://w3c.github.io/maturity-model/#ict-development-training

In the Updated version from myself it's: "Implementation of role-based training plans and curriculums"

They seem to overlap and so it's not clear where to place / evaluate them.
In both places does not seem to be the best approach...

Also there might be gaps in where to place training IF NOT PART of another dimension.
Like 'onboarding training" which is in Knowledge and Skills right now as it does not seem to fit any other dimension.

So, main question: Role Based Training in a 'Champion Model' is that by definition part of DLC? What is we have 'manager training'? General training? Agile coach training? Especially if this is not hardcore DLC? Do we need to fit it in "Culture"?"Support"? "Personnel"? And if it doesn't fit the Proof Points right now... make it fit by adding proper ones?

**Comment by Helixopp** [comment]
Training proof points have been added to each dimension. We believe the latest Editors Draft addresses this concern. If you still find an issue with it, please file a new GitHub Issue.
