### ISSUE TITLE
Where to place "internal support" for MSE or dedicated A11Y Team?

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#130]
https://w3c.github.io/maturity-model/#support

When you have SMEs or even a dedicated teams for accessibility and you provide very broad generic support internally for the whole organisation on all accessibility related questions, where does this fit in the Model?

When I look at the Support dimension, it seems that is the place to provide all kind of support for internal and external people with disabilities, but not providing support for employee having accessibility questions.

The 'support' part for accessibility can be a big part in a dedicated team or even important for the organization, and often this is not really seen as 'Training". 

Will / do we need to do something about this topic, or will we see this as part of "Dimensional Training" and see where it fit depending on the questions or who is asking?!

**Comment by Helixopp** [comment]
Thank you, for your comment. We have taken it into consideration, along with other feedback from the public, and significantly revised the document. We believe that we have addressed your concern. If it still persists, please open a new issue, and provide any supporting documentation, you would like
