### ISSUE TITLE
Update for dimension "Culture" + Spreadsheet example

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#131]
Based on:
https://www.w3.org/TR/maturity-model/#culture-proof-points

Have an updated version for dimension Culture which can be seen in the draft "Test Spreadsheet Simplified" - 3.7 Culture:
https://docs.google.com/spreadsheets/d/1sbfh2Kone3Poe9CGw-llOriBPK3GnGDj3YY2GmDZH80/edit#gid=467715868

The mapping between the 'old' and 'new' Outcomes and Proof Points can be seen in the attached Word document:
[CULTURE NEWEST.docx](https://github.com/w3c/maturity-model/files/9526126/CULTURE.NEWEST.docx)

Additional updates may come from the Outcomes at the Ratings.:
https://www.w3.org/TR/maturity-model/#culture-ratings-for-evaluation

**Comment by Helixopp** [comment]
The spreadsheet has been overhauled. Please review the new version. If any issues persists, please file them.
