### ISSUE TITLE
User Research is not User Experience

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#132]
=== Mail Received from K.H, CPACC Head of Accessible UX Design ===

Hi all,

Regarding the Maturity Model, I wanted to bring to your attention the difference between User Experience and User Research.
In section 3.4.1.3, the title of the section is "User Experience", yet the content is specific to "User Research". 

The design phase cited in section 3.4.1.1 includes tasks to be performed by roles such as User Experience (UX) Designers and User Interface (UI) Designers. The design phase is where the user's experience is crafted primarily by these 2 roles. Content Designers contribute of course, but UX and UI design the experience. 

The research phase can and should wrap the entire Software Development Lifecycle. The research is the gas that fuels additional features / updates (while also contributing to the initial design and launch of course). So the output of the research activities turns into requirements that UX and UI intake to craft the experience. It is absolutely possible to design without any research. You see? So the experience is crafted in design with or without research.

Therefore, I would recommend that you change the title of section 3.4.1.3 to "User Research".

K.H, CPACC
Head of Accessible UX Design

**Comment by swinehartganderson** [comment]
I see this already has an assignee, but I can take this up at the next task force meeting. I also have some clarifying questions on the design section and suggested edits.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
