### ISSUE TITLE
Address the accessibility of entire processes in the Maturity Model.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#137]
There are situations in which an organization's Web site satisfies reasonable accessibility requirements, but the entire process transacted with it does not.

For example:

* An organization requires part or all of a transaction to be completed via printed forms, which may be inaccessible to clients with visual or certain physical disabilities. It may be possible to initiate the process on the Web, but not to complete it in an accessible fashion. This is especially problematic if applicable law allows the transaction to be completed entirely online (e.g., with electronic signatures).

* It may be possible to register on an organization's Web site for an in-person event which takes place at a location that is inaccessible to people with certain physical disabilities. Participants may be unaware of this issue, and the organization may make no effort to address the problem.

I expect further examples can readily be given.

Such examples raise two related issues.

1. Should there be an expectation that transactions which it ought to be possible to complete entirely online can be so completed? How should this be recognized in the Maturity Model?

2. How should the organization's digital accessibility maturity relate to its broader accessibility maturity (e.g., concerning access to physical spaces)? Should there be a criterion in the Maturity Model addressing this relationship?

The underlying intuition is that an organization's digital accessibility maturity is low if important processes or transactions can't be completed entirely online or in an accessible fashion, even if the Web-based aspects meet accessibility standards. Correspondingly, an organization that integrates its approach to digital accessibility into a broader (more comprehensive) solution, and which attends to the accessibility of the entire transaction or experience, seems to  rank more highly in maturity.

**Comment by Helixopp** [comment]
We believe that this is out of scope.
