### ISSUE TITLE
Duplicated info?  Knowledge and Skills seemed to be repeated with the maturity stages section

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#138]
do we need this, or is it covered by outcomes and improvments?
Example: Communications sheet row B, no effort.
then B6 also says, no accessibility effort around communications
it seemed duplicative and confused them

**Comment by clapierre** [comment]
This connects with a discussion here about whether K&S should be its own section, or a proof point for every section
… Example, ICT section clearly needs K&S. So we decided to incorporate it in the ICT section

Sheri_B-H: ... our approach was to do both. The specific K&S goes in the proper section, and global K&S has its own section.

<Sheri_B-H> So the answer we ended up for in the draft is both: general K&S goes in K&S, specific knowledge for a dimension goes in the dimension
<Sheri_B-H> so an example would be ARIA - only ICT folx need training in that, so it goes in ICT

**Comment by clapierre** [comment]
In the introduction to K&S.

While this dimension includes proof points to be implemented at the organization level, knowledge and skills specific to each of the other dimensions should be included within their respective proof points, as appropriate.  For example, knowledge of ARIA is specific to ICT, so it is included as an ICT proof point.  Basic information on disability inclusion is generic and would be included in knowledge and skills.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
