### ISSUE TITLE
 'Business strategy includes accessibility as a market differentiator'

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#142]
Sheri_B-H: Show that the business is actually advertising that they are accessible, as when one company promotes that they are accessible, other companies in the space start to prioritize accessibility
… it's a kind of corporate peer pressure

CharlesL: May want to add the word, 'advertising'?

**Comment by clapierre** [comment]
Instead of  "marketing" or "advertising" vs. "promoting"
(Maybe global search & replace)

agreed to use the word "promoting" instead of marketing or advertising in the proof point that the language in the comment came from

3.7.1 Proof Points Culture proof points may include but are not limited to: Business strategy includes "promoting" digital accessibility as market differentiator.

Be carful Global S&R Marketing. don't replace market (the noun) just marketing (the verb)

**Comment by clapierre** [comment]
3.7.1 Proof Points Culture proof points may include but are not limited to: Business strategy includes digital accessibility as market differentiator - change to  Business strategy includes promoting digital accessibility as market differentiator

**Comment by Helixopp** [comment]
will edit 3.7.1 to say Business strategy includes promoting digital accessibility as market differentiator
