### ISSUE TITLE
communities of practice. Question, communities we serve?

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#143]
Sheri_B-H: No, we meant disability communities and disability-related NGOs

Jeff_Kline: I was thinking of internal communities of practice, internal to the company

**Comment by Helixopp** [comment]
Would like to get feedback from equity subgroup before editing the text.

**Comment by Helixopp** [comment]
We will add a definition for Communities of Practice.

**Comment by clapierre** [comment]
Definition to add is:
A community of practice is a group of people who share a common concern, a set of problems, or an interest in a topic and who come together to fulfill both individual and group goals.
Communities of practice often focus on sharing best practices and creating new knowledge to advance a domain of professional practice. Interaction on an ongoing basis is an important part of this.

**Comment by clapierre** [comment]
Also Link to this key term where appropriate in the document.
