### ISSUE TITLE
The effectiveness of knowledge/skill acquisition should be measured.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#153]
Section 3.2 suggests measuring the completion of training programs and monitoring them, but it doesn't explicitly refer to measures of their success with respect to improved performance in digital accessibility.

What ultimately matters is whether knowledge and skills are acquired and applied, leading to superior outcomes for users with disabilities. Thus, measures of improved performance following training could usefully be added.
Subsequently to the education/training, do those who received it actually perform better in the accessibility-related aspects of their roles? This could be monitored as part of the normal performance measuring procedures of the organization.

A more mature organization should have such evaluation in place (whether it be formal or informal), and the findings should consistently show a link between provision of education/training and improved performance in the relevant respects. Obviously, in a less mature organization, evidence of the effectiveness of education/training in relation to job performance is not collected, or, if it is collected, fails to show a consistently positive relationship.

This issue partly addresses issue #91.

**Comment by Helixopp** [comment]
We believe the latest draft of integrate and optimize outcome stages address this issue.
