### ISSUE TITLE
Section 3.5: proof points should consider whether people with disabilities actually were included in the workforce as a result of the efforts made.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#156]
Were people with disabilities actually employed by the organization as a result of its recruitement efforts? If not, were they at least in the applicant pool?
How satisfied are employees with disabilities with the support provided? (This obviously overlaps with the support section, and includes mentoring, etc.).

I think the proof points in this section should be expanded to take into account evidence of success (or lack of it) in the inclusion efforts.

**Comment by jeffkline** [comment]
We believe this has been addressed now in 3.5.2.1 and 3.3.2.2. of the maturity model document dated June 18:

3.5.2.1 Recruiting
- established goals for recruiting employees with disabilities
- hiring announcements with diversity statements encouraging and attracting applications from people with disabilities
- a gap analysis or needs assessment to understand where the business is falling short of including applicants with disabilities
- preferential hiring initiatives to recruit employees with disabilities, where not prohibited by law

3.3.2.1.Support Metrics and Goals
- Establish appropriate / meaningful goals and metrics for the support organizations, to measure and track progress towards achieving those goals.
