### ISSUE TITLE
Section 3.6: proof points should be expanded to take into account evidence of the outcomes of the procurement process.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#157]
This issue relates to issue #91.

In section 3.6, evidence of the outcomes of the procurement process should be considered in evaluating its maturity. Informally, after the fact, how accessible do the procured products and services turn out to be, compared with what the antecedent evaluation (prior to acquisition) would lead one to expect? Are there unexpected  defects/shortcomings that are only discovered after procurement? If so, this indicates a lack of maturity in the process, in that the issues should have been identified in the evaluation prior to acquisition.

* How well and how consistently do the procured products/services live up to the suppliers' claims about accessibility?
* To what extent do suppliers correct defects brought to their attention by the orgnaization, effectively and in a timely manner?
* How satisfied are employees, customers or others with disabilities who use procured products/services with their accessibility (once they've been deployed and used)?

I think factors such as these tend to reveal the maturity (or otherwise) of the procurement process, especially when these factors are evaluated across multiple procurements.

**Comment by Helixopp** [comment]
suggested resolution: Without requiring specific metrics and goals, we believe that our addition of metrics and goals resolves this issue, to the extent applicable by the maturity model.
