### ISSUE TITLE
Section 3.7: proof points should be expanded to consider whether inclusion is actually taking place.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#158]
This relates to issue #91.

I would suggest extending the proof points to take into account evidence of the degree to which the inclusive culture established by the organization is  actually resulting in inclusive practices.

* How satisfied are employees, customers and others with disabilities with their interactions with the organization? Do they believe they are being included appropriately and that their needs are being met? To what extent do they regard the organization's employees as open to learning more about the needs of people with disabilities and willing to improve practices further?

The underlying suggestion here is to evaluate the organization's culture, in part, by considering the quality of the interactions that take place with people with disabilities - evidence of the practical effects of the culture in concrete situations.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
