### ISSUE TITLE
Need plain langauge version of maturity model and examples

### ISSUE THREAD

**Issue by rachaelbradley** [w3c/maturity-model#162]
I have tried now, with others, to apply this model in two different scenarios. 

The proof points in the model are often unclear. Also, it is strongly geared to very large, bureaucratic organizations.  I believe the entire model would benefit from a plain language review, additional descriptions and examples, and indications of what key proof points are for small and medium organizations. 

The points that caused the largest confusion, both about what they meant and how they would be realistically applied are: 
- ACR/VPAT authoring guide for commercial off-the-shelf (COTS) products
- Hiring announcements with targeted diversity statements narrowing eligibility to applicants with disabilities
- Recruiting needs assessment/gap analysis
- Accessibility specific solicitation forms and templates
- Proof of accessibility criteria solicitation response evaluations
- Accessibility in Procurement Program Management:
```
-   Accessibility audits
-   Contract Life cycle management
-   Dashboard of Procurement related accessibility metric
-   Issue management process (for complaints)
```

**Comment by swinehartganderson** [comment]
This issue will be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
