### ISSUE TITLE
The application of the model to decentralized organizations could be clarified, as could the nature and roles of the valid outputs of applying the model in an evaluation.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#17]
It isn't entirely clear how the maturity model would apply to a decentralized organization in which different components are at different maturity stages along each of the dimensions. For example, a university may have faculties and departments which are relatively autonomous in their technology acquisition and Web content development, as well as a department responsible for the institution's main Web site. The group responsible for the main Web site may, for instance, be at a relatively advanced stage in all dimensions, whereas the faculties and departments could vary considerably along the dimensions.

Until consistent practices are developed and implemented across the entire institution, the results of evaluating the dimensions with respect to each faculty/department are going to yield varying outcomes. It isn't clear from the document how the model should be applied in such cases.

For instance, is the stage achieved by the entire organization along a given dimension determined by the stage reached by the worst-performing organizational component? For the purpose of improving and implementing a strategy, having a much more detailed record of maturity for each of the components of the organization could actually be more useful than an aggregate for the entire organization.

Is one also supposed to aggregate the results across all of the dimensions to assess the maturity of the entire organization? If so, is the maturity stage achieved by the organization the lowest stage reached in any of the dimensions?

As these questions suggest, I think the document could better define what the outputs of the maturity model are (e.g., a list of evaluations - one for each dimension, for the entire organization, as well as an aggregate maturity level - a single maturity "stage" reached). There are cases in which having evaluations for components of the organization would be useful, as suggested above, so if all of these different evaluations - and hence different outputs of the model are valid for different purposes, some discussion of this in the document would help to clarify the role of the model considerably.

Defining what the valid outputs of evaluation are and why each of them would be useful would contribute significantly to clarifying the use of the maturity model.

**Comment by jasonjgw** [comment]
I read section 1.2.1 before submitting this issue, but it didn't address the problems raised. All it says is that you can apply the maturity model to part of the organization rather than to the whole.

**Comment by jbuller** [comment]
I agree with this issue, I've faced it with other maturity models.
I feel there needs to be clarification on whether scores should be based on the lowest achieving department, the highest or an average. 
A more sophisticated approach would be some kind of additional weighting to show whether the practice is isolated, sporadic or pervasive.

Similarly, it would be helpful to cope with situations where you fail on one point but pass on several rates higher ones.

**Comment by Helixopp** [comment]
Consistent with other standards, such as IS?O 9000: The Task Force has agreed to add additional use cases in an appendix to provide examples. We do not believe we should instruct users on how to apply the model in this circumstance.
