### ISSUE TITLE
Proof Point Discrepancies between Specification and Template

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#172]
3.1.1.2 Accessible Direct Communications
(the following have sub points in the spec, just want to know if these are headers and shouldn't be included in a status update)

•	Consistent use of accessible templates for:

•	Internal and external websites:

•	Products and services: accessibility compliance documentation is available and delivered in an accessible format (on the website, by request, or through procurement process)

-------

The following is included in the Template but not included in the spec.

User Experience
User research includes disabilities
- All research asks participants to anonymously identify whether or not they have a disability, and if so, what type of disability/ies
User research focusing only on disabilities is performed
Quality Review Through Release
Consistent approach to testing and releasing products
Testing process documents steps for manual accessibility testing, utilizing assistive technology
Testing process includes automated accessibility testing
Schedule includes stakeholder activities focused on accessibility
Bug tracking system includes an accessibility category
Prioritization and grooming system for accessibility defects
Accessibility identified as product release gate
Documented testing steps and cadence for agile delivery of changes that do not go through a full release cycle. Some examples are:
- Content review for website updates
- Content review for social media posts
ACR/VPAT authoring guide for commercial off-the-shelf (COTS) products

-------

Support Dimension 

Entirely out of sync.

-------

3.4.1.1 Design
•	Design work products delivered to developers include accessibility information that at least meets relevant accessibility standards
Vs. in excel:
•	Design artifacts delivered to developers include accessibility information that at least meets relevant accessibility standards

-------

3.4.1.2 Development
Is this a Header?
Accessible developer implementation resources

-------

3.4.1.3 User Experience
Is this a Header?
User research includes disabilities

-------

3.4.1.4 Quality Review Through Release
Is this a Header?
Documented testing steps and cadence for agile delivery of changes that do not go through a full release cycle. Some examples are:

-------

This is missing from the Template

3.5.1.2 Accessible Job Application Platform
•	Hiring tools, job boards, etc. meet a specified level of accessibility
•	Recruiting communications meet a specified level of accessibility
•	Accessibility audit of Jobs' website
•	Accessibility audit of application process

-------

3.6.1.1 Policy Documentation
•	Published ICT accessibility policy
Vs (from template)
•	Published ICT Accessibility Policy / Procurement Policy

-------

3.6.1.3 Consistent Evaluation Process and Methods
•	Proof of accessibility evaluations
Vs (from template)
•	Proof of accessibility criteria solicitation response evaluations

**Comment by Helixopp** [comment]
We will also address # 79
The outcomes for the support dimension optimize stage says:

Employees/Talent Acquisition: Candidates are offered accommodations for their interviews. Disability Employee Resource Group(s) provide social and professional support to employees with disabilities.

This is confusing since all of the proof points in the support dimension are about supporting employees with disabilities and supporting customers with disabilities. and are not related to talent acquisition at all, which are covered instead in the Personnel dimension.

**Comment by Helixopp** [comment]
Is this issue still present? Or did we resolve it with the June update?

**Comment by clapierre** [comment]
@Helixopp we haven't synced up the model with the excel spreadsheet.

**Comment by Helixopp** [comment]
Issue resolved with Issue #228
