### ISSUE TITLE
Question 3.2 Knowledge&Skills Proof point (row 27)

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#179]
In the excel spreadsheet

What does this mean exactly and how would you rate which stage?

3.2 Knowledge&Skills

Proof point (row 27)
Training and learning programs should be integrated into proof points for each dimension

**Comment by Helixopp** [comment]
Is this issue still present? Or have we resolved it with the June draft?

**Comment by clapierre** [comment]
Still an issue in the spreadsheet @Helixopp

**Comment by jeffkline** [comment]
Changed the row 27 proof point in the Knowledge and Skills spreadsheet tab from:
Training and learning programs should be integrated into proof points for each dimension

To:
Training and learning proof point(s)(one or multiple as needed) should be developed and included in the proof points for each dimension
