### ISSUE TITLE
What's the relationship with ISO/IEC 30071-1:2019?

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#18]
There is considerable overlap between this document and the practices recommended in ISO/IEC 30071-1:2019, in that both are concerned with an organization's policies and processes. However, the ISO standard is more detailed and specific in important respects. For example, it specifies what should be done at each stage of the ICT system development and maintenance process, and what matters should be addressed in an organization's accessibility policy (then reflected in its policies and procedures with respect to ICT).

The ISO standard also extends beyond conformance with technical accessibility guidelines such as WCAG to address issues of "efficiency", "effectiveness" and "satisfaction" of users with disabilities in interacting with ICT-based systems.

It isn't clear from the maturity model document how it is meant to relate to the ISO work. While it doesn't treat all of the same issues as ISO/IEC 30071-1:2019, the overlap of concerns is sufficient to raise questions about consistency between the two, whether organizations should use both, and how maturity model analysis relates to an organization's decisions about conforming to the ISO standard.

**Comment by jake-abma** [comment]
Thank you for bringing this issue to our attention. We will review accordingly.

**Comment by Helixopp** [comment]
The W3C, and ISO, do not share a mandate for cross compatibility. This Maturity Model was not intended to relate toISO/IEC 30071-1:2019. It is up to each organization how they want to use ISO and/or W3C guidance.

That being said, I have reviewed ISO/IEC 30071-1:2019 and it is my belief that they ar complimentary to each other.
