### ISSUE TITLE
Word "utilized" seems off

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#180]
Persons with disabilities should be **utilized** throughout an organization’s hierarchy (all job types, all authority levels) where their unique insights and lived experiences should better inform decision making. This requires accessible and inclusive hiring practices covering application, interviews, evaluations, onboarding and retention.

Is there a better word other than "utilized" we can use here please?

**Comment by swinehartganderson** [comment]
This was updated in the "usability" doc to: 
People with disabilities with the necessary experience should be hired throughout an organization’s hierarchy (all job types, all authority levels), where their unique insights and lived experiences can better inform decision-making.

**Comment by swinehartganderson** [comment]
This issue will be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
