### ISSUE TITLE
Manager took questioned the word "narrowing" 

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#181]
-Hiring announcements with targeted diversity statements narrowing eligibility to applicants with disabilities

Our hiring manager was taken aback at this statement, in that she didn't feel right actively trying to "narrow" the field -reverse discrimination was brought up etc.

**Comment by clapierre** [comment]
maybe “attracting” hiring most qualified.

**Comment by swinehartganderson** [comment]
I agree. I'll include this change with the "Usability" doc.

**Comment by swinehartganderson** [comment]
This issue will be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
