### ISSUE TITLE
New Table column order reversed

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#183]
Minor Nitpick, In our specification under

4.1 Internal resources needed to implement the maturity model at your organization

In the table I noticed Column "Procurement" comes before "Personnel" everywhere else "Personnel" is first.
Minor issue I know

**Comment by Helixopp** [comment]
Is this in the spreadsheet? @clapierre iscthis issue still present? Or can we resolve it with the June updated draft

**Comment by clapierre** [comment]
Still an issue in [Table 4.1 of our Note](https://www.w3.org/TR/maturity-model/#internal-resources-needed-to-implement-the-maturity-model-at-your-organization)

**Comment by Helixopp** [comment]
@clapierre will update table to match document order
