### ISSUE TITLE
letter "s" must become "small"

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#19]
> It is designed to work for many different size organizations from s to large corporations or government agencies.

letter "s" must become "small"

> It is designed to work for many different size organizations from **small** to large corporations or government agencies.

**Comment by joshueoconnor** [comment]
Seems to be fixed in main, thanks @jake-abma

**Comment by joshueoconnor** [comment]
Am reopening until I'm sure what branch I should be working in - @Helixopp

**Comment by joshueoconnor** [comment]
Can be closed
