### ISSUE TITLE
Excel Spreadsheet 3.2 Communication Tab 

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#190]
Should the proofpoint on row 22 in the communication tab be a header row?

I.e.
Internal and external websites:

since below that there
 - are accessible per regional regulatory requirements (e.g. conforms to WCAG)
 - may have an accessibility statement (legal requirement for websites for public sector bodies in the European Union)
 - may contain a statement of commitment to accessibility

**Comment by Helixopp** [comment]
@clapierre is this issue still present? Or can we resolve it with the latest June draft?

**Comment by clapierre** [comment]
Still an issue @Helixopp

**Comment by jeffkline** [comment]
Updated to change Internal and external websites to a header line, and modified the formulas to reduce the total proof points in the dimension to 35 from 36. 

I also hard coded the total proof point totals for each dimension in Column H of the Full Tally tab.
