### ISSUE TITLE
W3C Accessibility Maturity Model Feedback:

### ISSUE THREAD

**Issue by newtonsgroove** [w3c/maturity-model#191]
Here is the content reformatted for pasting into a GitHub issue:

# The latest Excel document (https://github.com/w3c/maturity-model/blob/main/A11yMaturityTemplate.xlsx) has many more sections of proof points than are listed in the document online. Why is there such a difference? Is this an oversight or information that should be reorganized in one of the platforms? Example:

### User Experience

- User research includes disabilities
  - All research asks participants to anonymously identify whether or not they have a disability, and if so, what type of disability/ies
- User research focusing only on disabilities is performed

### Quality Review Through Release

- Consistent approach to testing and releasing products
- Testing process documents steps for manual accessibility testing, utilizing assistive technology 
- Testing process includes automated accessibility testing
- Schedule includes stakeholder activities focused on accessibility
- Bug tracking system includes an accessibility category
- Prioritization and grooming system for accessibility defects
- Accessibility identified as product release gate
- Documented testing steps and cadence for agile delivery of changes that do not go through a full release cycle. 
  - Content review for website updates
  - Content review for social media posts
- ACR/VPAT authoring guide for commercial off-the-shelf (COTS) products

### Organizational Support

- Establish policies, practices and procedures for providing accessible customer service
- Ensure that all information is presented in plain language
- Support mechanisms are accessible
- Help topics or FAQs specific to accessibility in the internal documentation of the organization
- Validation process in place to manage accessibility feedback
- Accessibility feedback is incorporated to facilitate continuous improvement of identified ICT and internal tools
- Any feedback plan incorporates an accessible way of responding to the employees that provided the feedback with updates about the state and decisions on the feedback.
- Involve people with disabilities in the planning and implementation of accessibility initiatives

### Staff Support Training Programs

- Staff training programs are in place to build and maintain relevant skills in support of this dimension’s proof points.
- Provide training for internal ICT support staff in accessibility, assistive technology and disability etiquette and awareness
- Provide training cross-company about disability etiquette and awareness  
- Provide training for customer support staff in accessibility, assistive technology and disability etiquette and awareness

#### Customer Support

- Publicly available (and accessible) digital accessibility statement with pointers to support mechanisms
- Written policy on requesting and providing customer accommodations, if applicable
- Establish a process for receiving and responding to feedback on accessibility
- Provide help topics or FAQs questions specific to accessibility in an accessible format
- Have processes put on place to guarantee that code from third parties or provided by external vendors are accessible
- Provide accessible options and support to any step or functionality that depends on an inaccessible feature with technical impossibilities to be remediated. e.g.: Identity Validation processes
- Provide accessible formats and communication support including visual platforms for people which primary language is Sign Language
- Ensure that newly procured or developed digital documents offered to the customers are accessible
- Create a plan to make accessible all past digital documents available for the customers
- Ensure that all information is presented in plain language
- Provide a specific channel for customers to report accessibility issues or blockers in an easy and accessible way. e.g.: dedicated email address
- Any feedback plan incorporates an accessible way of responding to the customers that provided the feedback with updates about the state and decisions on the feedback.
- Ensure that customers with disabilities can use their own assistive technology or assistive technology of their preference to access your goods and services

**Comment by Helixopp** [comment]
@newtonsgroove is this issue still present? Or can we resolve it with the latest June draft?

**Comment by newtonsgroove** [comment]
I think we can close this and review alignment with the next release
