### ISSUE TITLE
Excel Spreadsheet: Personnel Dimension Concerns

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#194]
For the proof points:
-  Established goals for recruiting employees with disabilities
-  Preferential hiring initiatives to recruit employees with disabilities

Feels like a quota (Concerned about legal ramifications)

- Recruiting needs assessment/gap analysis
What does this mean?

**Comment by jeffkline** [comment]
Modified language of proof points in A13 - A15 as shown below:

- Actively recruit qualified candidates with disabilities
- Hiring announcements with diversity statements encouraging applications from people with disabilities
- Recruiting  / employee populations consistent with typical ratios of general population / PwD populations demographics
