### ISSUE TITLE
Excel document link is broken

### ISSUE THREAD

**Issue by wittjeff** [w3c/maturity-model#203]
Link: https://www.w3.org/TR/maturity-model/A11yMaturityTemplate.xlsx
Page where it appears: https://www.w3.org/TR/maturity-model/#assessment-template-excel

**Comment by clapierre** [comment]
Hi Roy,
Oh, I guess you also need to make a copy of the latest version of our Excel spreadsheet as well.
Can you please make a copy and put it where the document expects it please in the latest Working Draft folder.

Nice Catch Jeff.

Thanks
Charles
EOM

From: Jeff Witt ***@***.***>
Sent: Tuesday, December 19, 2023 10:13 AM
To: w3c/maturity-model ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [w3c/maturity-model] Excel document link is broken (Issue #203)


Link: https://www.w3.org/TR/maturity-model/A11yMaturityTemplate.xlsx
Page where it appears: https://www.w3.org/TR/maturity-model/#assessment-template-excel

**Comment by clapierre** [comment]
Thank you for this, I fixed now.

Best,

Roy

**Comment by clapierre** [comment]
Roy has fixed this, marking it closed.
