### ISSUE TITLE
Flow of "A Maturity Model is:" need a little bit of love

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#21]
Change...

> A Maturity Model is:
> 
> A tool;
> 
> That helps people assess the current effectiveness of a person, group, or an organization;
> And supports figuring out what capabilities they have and need to acquire next;
> In order to improve their performance.

To something like...

[... Next sentence... ]
> A Maturity Model is  a tool that helps:
> 
> Assess the current effectiveness of a person, group, or an organization;
> Supports figuring out what capabilities they have and need to acquire next;
> Improve performance.

**Comment by clapierre** [comment]
Where is this located?  I don't see it in our current [documentation](https://w3c.github.io/maturity-model/).

**Comment by Helixopp** [comment]
This section has been updated. Please reopen issue if you are not satisfied
