### ISSUE TITLE
Excel spreadsheet - broken link

### ISSUE THREAD

**Issue by luce-carevic** [w3c/maturity-model#213]
The link for the Excel spreadsheet is broken: https://www.w3.org/TR/maturity-model/A11yMaturityTemplate.xlsx

**Comment by Helixopp** [comment]
W3C Staff will fix this issue

**Comment by ruoxiran** [comment]
https://www.w3.org/TR/maturity-model/ updated, Charles @clapierre , I replied to your email from here, can you help review it if there are any other issues?

**Comment by clapierre** [comment]
This is now working as expected. Thanks @ruoxiran
