### ISSUE TITLE
Remove VPAT References

### ISSUE THREAD

**Issue by Helixopp** [w3c/maturity-model#216]
We need to be careful not to promote, or endorse third party products. VPAT's are a proprietary, Registered, product of ITI. We need to remove those references. An Accessibility Conformance Report is a good enough term..

Accessibility conformance reports (ACR) based on the [Voluntary Product Accessibility Template®](https://w3c.github.io/maturity-model/#dfn-vpat) (VPAT)

**Comment by clapierre** [comment]
As discussed in our [7/24/24 meeting](https://www.w3.org/2024/07/24-maturity-minutes.html)
Remove VPAT reference and include with mentions of ACR -  Industry recognized standard
