### ISSUE TITLE
Key Terms: Contract Lifecycle

### ISSUE THREAD

**Issue by clapierre** [w3c/maturity-model#217]
contract lifecycle
The steps and processes related to the procurement of an ICT product or service beginning with the initialization of the solicitation process, response evaluations, vendor selection for award, implementation of the contract requirements, monitoring over the life of the contract including renewals until the contract reaches its end date.

**Comment by Helixopp** [comment]
@jeffkline please respond with a comment on this issue

**Comment by jeffkline** [comment]
Looks good!

**Comment by Helixopp** [comment]
I'm confused. Is this an issue? Can it be closed?

**Comment by jeffkline** [comment]
Yes
