### ISSUE TITLE
2.4.1 Maturity Model Excel Spreadsheet Should be Deleted

### ISSUE THREAD

**Issue by Helixopp** [w3c/maturity-model#234]
2.4.1 Maturity Model Excel Spreadsheet

**Current Form:**

This is the [latest Accessibility Maturity Model excel spreadsheet](https://www.w3.org/TR/maturity-model/A11yMaturityTemplate.xlsx) containing seven sheets one for each [dimension](https://www.w3.org/TR/maturity-model/#dfn-dimension) as well as a cover sheet where a list of all changes made have been recorded.

We encourage you to make a copy of the assessment template worksheet to get started.

EDITOR'S NOTE
The Maturity Model assessment worksheet is intended as a high-fidelity prototype to measure organizational maturity and was developed in an Excel format. The final published format is to be determined, but is envisioned as HTML. It may also be made available in other downloadable, accessible formats.
EDITOR'S NOTE
This spreadsheet is experimental and is a work in progress. The [proof point](https://www.w3.org/TR/maturity-model/#dfn-proof-point) in this document may not be in sync with the supporting Excel spreadsheet template. The Excel spreadsheet template has the most up-to-date [proof point](https://www.w3.org/TR/maturity-model/#dfn-proof-point).

**Suggested Edits**

Editors Notes should be moved up to section 2.4 in the edited version I provided in Issue #233. The information provided in 2.4.1 is redundant. 2.4 provides a link to the template along with instructions.

**Comment by clapierre** [comment]
I am fine bringing the contents of 2.4.1 up into 2.4 (Assessment Template) and removing sub-section 2.4.1.  since the excel spreadsheet is the only "Assessment Template" we have so doesn't make sense to have it be in its own sub-section.

**Comment by jeffkline** [comment]
I also agree. My proposed rewrite to be 2.4 only is below. Note that when reviewing this section (2.4) of the document, I found that there was other information that needed updating.

**2.4 The Maturity Model Assessment Tool** 
Organizational ICT Accessibility Maturity is assessed using the Accessibility Maturity Model Assessment Tool template. 
Instructions on how to complete the assessment are included in a worksheet tab within the assessment tool template. Assessment results should be based on relevant, documented evidence that explains why each proof point has reached a particular maturity level. 

Here is the [link to the Accessibility Maturity Model Assessment Tool template](https://w3c.github.io/maturity-model/A11yMaturityTemplate.xlsx) (in excel spreadsheet format). The tool contains:
•	A cover sheet tab where a list of changes made have been recorded.
•	An instructions tab that explains how to assess proof point maturity levels
•	Seven tabs, one for each [dimension](https://w3c.github.io/maturity-model/#dfn-dimension) and its associated proof points
•	A scoring tab that tallies and registers results and progress of the dimension assessment tabs

The dimension tabs are where the assessment is performed. Each of those tabs contain the dimension definitions and general outcomes for each of the four [maturity levels](https://w3c.github.io/maturity-model/#dfn-maturity-level) and provides a list of proof points to be assessed specific to each dimension.
It is possible to customize the template with additional proof points if needed by inserting a line and adding the new proof point statement.

It is encouraged that you to make a copy of the assessment tool template to get started.

EDITOR'S NOTES
1.	The proof points as defined in the Maturity Model document may not exactly match the proof points contained within the Maturity Model Assessment Tool template. 
The template contains the most up to date proof points defined by the Maturity Model Task Force and should be considered as “incorporated by reference” into this Maturity Model document.
2.	The Maturity Model Assessment Tool is a high-fidelity prototype and continues to evolve. The current version of the tool is in Excel format. Final published formats are still being considered, but envisioned as HTML. The tool may also be made available in other downloadable, accessible formats.

_______________________________________________________________________________
Note to the Task Force: I recommend that we replace the term “spreadsheet” with “assessment tool.”  This is a more meaningful characterization of what it is, and is technology neutral, regardless of the final technology selected.

**Comment by Helixopp** [comment]
Proposed rewrites to 2.4 should be posted to Issue #233

**Comment by Helixopp** [comment]
Resolution has been completed
