### ISSUE TITLE
No "Appendix" present for "1.3 Existing Research" (Delete?)

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#28]
See 1.3:

> 1.3 Existing Research
> Reference appendix with summary of the existing six maturity models outside of WCAG.

Now...

1. There is no appendix in the document
2. There are more than 6 'in the wild', it reads like "THE 6 Models", which should not be mentioned that way.

Delete 1.3 OR mention "Some models researched"

**Comment by clapierre** [comment]
I believe this has been done, as I don't see this mentioned anymore in [section 1.3](https://w3c.github.io/maturity-model/#existing-research)

**Comment by Helixopp** [comment]
Appendix deleted
