### ISSUE TITLE
" Dimensions include:" change to " Dimensions included:"

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#31]
" Dimensions include:" change to " Dimensions included:"

Also...

1. Delete space before "Dimensions include:"
2. "enter" before "Dimensions" so it goed to next sentence

Change:

>  Dimensions include:
> 
> Communications
> Knowledge and Skills
> Support
> ICT Development Lifecycle
> Personnel
> Procurement
> Culture

To:

> Dimensions included:
> 
> Communications
> Knowledge and Skills
> Support
> ICT Development Lifecycle
> Personnel
> Procurement
> Culture

**Comment by joshueoconnor** [comment]
This looks like it is no longer relevant? The current note and editors draft are in sync and sensibly outline the dimensions.
