### ISSUE TITLE
"three levels" is "four levels" now...

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#33]
Change:

`The Maturity Model has three levels of content with associated documentation.`

to:

`The Maturity Model has four levels of content with associated documentation.`

Inactive
Launch
Integrate
Optimize

= 4

**Comment by jake-abma** [comment]
ands... change "Levels" to "Stages" to be consistent.

**Comment by Helixopp** [comment]
edited the levels to stages

**Comment by joshueoconnor** [comment]
This comment seems to be dealt with in the current note (or at least seems quite developed here) https://www.w3.org/TR/maturity-model/?

**Comment by joshueoconnor** [comment]
Can be closed
