### ISSUE TITLE
"Stages based on proof points" not correct

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#35]
Depending on the method chosen (spreadsheet), the stages in NOT by definition based on the proof points...

Change:

> Each dimension will contain stages” based on the proof points that are demonstrated.

To:

> Each dimension will contain stages” based on the proof points that are demonstrated.

(btw, we've chosen the stages 'based' on other factors than proof points at all)

**Comment by Helixopp** [comment]
We have substantially revised the Working Draft, and believe it has resolved this issue. If it still persists, please open a new issue
