### ISSUE TITLE
Adjust paragraph

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#36]
Change:

> Stages loosely correspond to the following criteria. Each dimension will contain defined criteria that pertain specifically to the dimension being defined. Stages are cumulative, so stage advancement cannot be achieved without first meeting the specific criteria of a lower level. The terms for the stages were adopted for consistency with the Policy Driven Adoption Maturity Model, currently being used by multiple government agencies.

To:

> Stages loosely correspond to the following criteria:
> 
> - Each dimension will contain defined criteria that pertain specifically to the dimension being defined.
> - Stages are cumulative, so stage advancement cannot be achieved without first meeting the specific criteria of a lower level.
> 
> The terms for the stages were adopted for consistency with the Policy Driven Adoption Maturity Model, currently being used by multiple government agencies.

**Comment by Helixopp** [comment]
The draft has been updated. If you still have editorial recommendations please open a new issue
