### ISSUE TITLE
Launch should not be dependent on "organization-wide."

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#38]
Level "Launch" mentions:

> Launch | Recognized need **organization-wide**. Planning initiated, but activities not well organized.

Often ideas get launched while there is not a 'recognized need :"**organization-wide**"', and still counts as a good starting point to get accessibility on the agenda putting you at level 1.

Also the AMM can be used for parts of the organization, making this even more important NOT to demand **organization-wide**

Should be changed to:

 > Launch | Recognized need in the organization. Planning initiated, but activities not well organized.

**Comment by Helixopp** [comment]
I think I agree with you. Will discuss as a group.

**Comment by Helixopp** [comment]
Thank you. We agree with your suggestion.
