### ISSUE TITLE
Change definition of K&S

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#39]
K&S definition is missing 'insight of knowledge'

Change:

> Knowledge and Skills: Education and outsourcing practices to fill gaps for accessibility operations.

To:

> Knowledge and Skills: Insight of working experience, education, and outsourcing practices to fill gaps for accessibility operations.

**Comment by Helixopp** [comment]
A new draft has been published. If you still have editorial recommendations please open a new issue
