### ISSUE TITLE
Change Personnel definition

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#40]
Read as three separate parts, while everything after "disability-related employee resource groups" applies to all

Change:

> Personnel: Job descriptions, recruiting, disability-related employee resource groups necessary to provide lived-experience to accessibility efforts.

To:

> Personnel: Lived-experience to accessibility efforts for job descriptions, recruiting, and disability-related employee resource groups.

**Comment by Helixopp** [comment]
A new draft has been published. If you still have editorial recommendations please open a new issue.
