### ISSUE TITLE
Split definition for Culture in 2 sentences

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#41]
Change:

`Culture: The attitudes, sensitivity, and behaviors around accessibility, including internal interaction, perception, and decision-making.`

To:

> Culture: Attitudes, sensitivity, and behaviors around accessibility. Including internal interaction, perception, and decision-making.

**Comment by Helixopp** [comment]
A new draft has been published. If you still have editorial recommendations please open a new issue.
