### ISSUE TITLE
Section 3.1 (communication) should be clarified.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#42]
There are two topics in this section: (1) communication about accessibility, and (2) the accessibility of communications themselves - whether or not they are about accessibility.

I think the two issues should be clarified and better distinguished in a revision of the text.

The headings of subsections under 3.1.1 don't clearly describe the content of the subsections. The proof points are only briefly stated, and it isn't clear what is required to satisfy them (e.g., what a "statement of commitment" or an "accessibility statement" is, and what either of them should contain).

"Voluntary Product Accessibility Template" should include a bibliography reference that cites the official documentation. The same holds for "model accessibility statement".

In section 3.1.2, it isn't clear that the items listed under the "Optimize" level relate to communications - they appear to be more about organizational governance.

The relationship between "proof points" and "ratings for evaluation" could be clarified in general (e.g., the "proof points" describe what evidence to acquire, and the ratings describe what the evidence needs to show to achieve different levels of maturity along the dimension).

**Comment by jake-abma** [comment]
Thank you for bringing this issue to our attention. We will review and edit accordingly.

**Comment by Helixopp** [comment]
We are reviewing this section to address your concerns. We will close this issue once we have updated the section.

**Comment by Helixopp** [comment]
There are multiple issues here, some of which we can agree to, others that require more discussion.Please break this issue up into individual components

**Comment by Helixopp** [comment]
This topic has been discussed at length. We are currently discussing it with organizations that are experimenting with the model. We will respond
