### ISSUE TITLE
Should "proof points" and "ratings for evaluation" sections be combined for clarity?

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#43]
The "proof points" and "ratings for evaluation" are currently in different subsections of each section. it isn't clear, for instance, which proof points relate to which level of maturity. The reader also has to move back and forth between the subsections to understand what evidence establishes which outcomes.

Can this material be reorganized and, perhaps, combined to make it clearer?

**Comment by swinehartganderson** [comment]
@jasonjgw I'm taking a look at this issue and would love to test out a couple of ideas with you through here with a Google Doc link. Would you be open to taking a look and letting me know if the ideas start to offer better clarity and usability? (If you're using a screen reader and the Google doc isn't working correctly, please let me know.)

If yes, please check out this idea: [https://docs.google.com/document/d/1Wrhomdc2gJWIkDPOveiH3_ig1bddTMonEhIDZIzohrc/edit?usp=sharing]

Using 3.1 Communications as the example. 

- I added a short section about the ratings and levels in a simplified view before the proof points. 

- After the proof points, I edited the header for 3.1.4. The table in that section remains as-is in this instance.

Thanks!

**Comment by jasonjgw** [comment]
Moving the ratings so that they appear before the proof points seems reasonable. I apologise for the slow response; I missed the notification of the update to this issue.

**Comment by swinehartganderson** [comment]
No worries! I also miss the notifications. I'll share this with the task force to get their feedback on this approach as well.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
