### ISSUE TITLE
Would it be better to avoid the overlap between section 3.3 and sections 3.1 and 3.2?

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#45]
Many of the proof points and outcomes in section 3.3 appear to be covered under Communications and under Knowledge and Skill (sections 3.1 and 3.2).

Is this overlap desirable? If so, perhaps it should be noted somewhere in the document. I suppose one could argue that it is desirable to enable 3.3 to be evaluated completely independenty of having evaluated 3.1 or 3.2.

**Comment by Helixopp** [comment]
Please review the latest editors draft. We believe that ewe have resolved this issue. If you still have concerns please file a new issue, or reopen this one.
