### ISSUE TITLE
Requirements in section 3.4 could be clarified.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/maturity-model#46]
Although section 3.4 includes proof points and ratings related to design, implementation, and evaluation, it doesn't relate these to actual outcomes with respect to the accessibility achieved for people with disabilities. For example, it doesn't specify that the organization has identified the standards to which it is going to conform, or the criteria of accessibility (e.g., in terms of effectiveness/efficiency/satisfaction) to be achieved.

Nowhere does it state that the design, implementation and testing procedures are sufficient to achieve the desired standards and outcomes, if they are implemented correctly.

Describing requirements for ICT design, development, testing and maintenance is one of the areas in which the ISO 30071-1:2019 standard is particularly strong - but it isn't the only focus of that standard.

I suggest reworking this section to relate it more clearly to the suitability of the processes and procedures for actually achieving defined outcomes (e.g., meeting technical standards or satisfying criteria of usability/accessibility for users who have disabilities). For example, the design and testing procedures need to enable achievement of the organization's accessibility objectives (defined in terms of standards or other criteria).

As currently written, it seems to me that one could do everything described in this section and not achieve good outcomes or standards conformance.

**Comment by Helixopp** [comment]
Response. We will review and revise this dimension. Once we update the Dimension we will close this issue

**Comment by Helixopp** [comment]
we added a Dimension Goals and Metrics section after the ticket was logged to address this issue
