### ISSUE TITLE
 2.4.13 Focus Appearance (Enhanced) still got "Not obscured"

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#59]
Maybe I missed something or it is not updated yet but  2.4.13 Focus Appearance (Enhanced) still got "Not obscured" as last bullet

https://w3c.github.io/wcag/guidelines/22/#focus-appearance-enhanced

**Comment by mbgower** [comment]
At the AA level, we broke out the Not obscured wording into a separate SC https://w3c.github.io/wcag/guidelines/22/#focus-not-obscured

I will attempt to address this with a single PR that addresses both this and the differences in language between the minimum and enhanced versions

**Comment by mbgower** [comment]
@jake-abma Did you intend to open this in wcag, not maturity model? 
I will address regardless, but I cannot assign myself since I am not in this project.

**Comment by alastc** [comment]
NB: I can't move this, it would need someone with merge access to both repos I think. I don't know if anyone has that, so might need Jake to move it.

**Comment by maryjom** [comment]
@alastc I think I have access to both, but I don't think you can move an issue from one repo to another.

**Comment by alastc** [comment]
@maryjom it's on the right if available, I don't think you have full (merge) access on wcag, though. Michael has got a PR open for it that I'll use, you can close this issue.

**Comment by jake-abma** [comment]
Oeps, see I've added more here, will add to WCAG...

**Comment by jake-abma** [comment]
moved to: https://github.com/w3c/wcag/issues/2392
