### ISSUE TITLE
3.3.2 Ratings for Evaluation - Support section: why is knowledge and skills mentioned?

### ISSUE THREAD

**Issue by maryjom** [w3c/maturity-model#78]
The last bullet of the outcomes for the Launch maturity stage of the Support dimension says "No external support for K&S". Does that mean Knowledge and Skills? Why is that being talked about in the ratings for the Support Dimension?

**Comment by swinehartganderson** [comment]
We're working on some updates with the ratings and evaluations for the entire model that will address this issue.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
