### ISSUE TITLE
Section 3.3.2 Rating for evaluation - Support: Outcomes for optimize stage don't align with proof points

### ISSUE THREAD

**Issue by maryjom** [w3c/maturity-model#79]
The outcomes for the support dimension optimize stage says:
>Employees/Talent Acquisition: Candidates are offered accommodations for their interviews. Disability Employee Resource Group(s) provide social and professional support to employees with disabilities. 

This is confusing since all of the proof points in the support dimension are about supporting employees with disabilities  and supporting customers with disabilities. and are not related to talent acquisition at all, which are covered instead in the Personnel dimension.

**Comment by sheribyrne** [comment]
This needs to be assigned to David, he owns both personnel and support

**Comment by Helixopp** [comment]
This issue will be addressed in Issue #172 Proof Point Discrepancies between Specification and Template

**Comment by jeffkline** [comment]
Closed and replaced by Issue #198
