### ISSUE TITLE
Inconsistencies in Inactive ratings for various dimensions

### ISSUE THREAD

**Issue by maryjom** [w3c/maturity-model#85]
For consistency, all maturity stages should have a definition and outcomes for every dimension. This is true except for two cases:

- 3.3.2 Ratings for Evaluation - Support: Inactive stage has no outcomes listed.
- 3.6.2 Ratings for Evaluation - Procurement: Inactive state text that is there should be identified as a definition.  It is also missing outcomes.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
