### ISSUE TITLE
Link to the worksheet needed from each dimension

### ISSUE THREAD

**Issue by maryjom** [w3c/maturity-model#86]
This was a suggestion that Jeff Kline proposed in the Google doc that has not yet been carried out in the maturity model document. I don't know if the group had reached consensus on adding this or where to add it, as the discussion in Google had different ideas on placement of the link: at the end of each ratings for evaluation section or at the beginning of that section were both mentioned. There's also the possibility of adding it at the beginning of the section that breaks down the dimensions.

**Comment by maryjom** [comment]
At the July 20 meeting we made a resolution to have a link at the top (where it is now) that links to the downloadable spreadsheet, and then for each dimension to have a link before the ratings for evaluation table that links to the particular tab in the spreadsheet for that dimension.

**Comment by Helixopp** [comment]
We have added a link to the spreadsheet in every dimension. We believe the latest working draft addresses this issue. If it still persist please reopen the issue or file a new one
