### ISSUE TITLE
3.6.1 Proof Points for Procurement Section: Some bullets aren't clear what is needed

### ISSUE THREAD

**Issue by maryjom** [w3c/maturity-model#87]
I find the proof points in procurement a bit confusing and it doesn't really say what is really needed and who does it.  These bullets are too brief to explain it.

In procurement, it's the vendor that should provide proof of due diligence in meeting accessibility requirements. If a procuring organization wants accessible products, they may be specific about what standard(s) they expect the ICT to meet and what proof they wants to see from the vendor. That should be built into the procurement and/or solicitation language. 

For the program management part, this is about establishing and managing the process, making sure the procurement steps and language the organization requires are being done and collecting and monitoring metrics around that. Whether or not they actually have a "dashboard" isn't the important part. 

What is the "Accessibility audit" part about? Need to be more specific about what you are auditing for. Are you testing the procured ICT, auditing that procurement personnel are following the process, and/or measuring the number of employee complaints?  Not sure how "Issue management" comes into play here. Issues on what and reported by whom?

**Comment by sheribyrne** [comment]
Will assign to Jeff after he is added to github

**Comment by Helixopp** [comment]
We have updated the entire Maturity Model document, including the Procurement section. We believe the update addresses your issues of concern. If they still persist, please open a new issue
