### ISSUE TITLE
ICT Development Lifecycle ratings outcomes aren't stated like the outcomes are in Silver

### ISSUE THREAD

**Issue by maryjom** [w3c/maturity-model#89]
There's some aspect of this in all of the ratings sections, but it became super-obvious to me in 3.4.2 Ratings for Evaluation for the ICT development lifecycle that the outcomes:

- The language does't seem to align in the type of language used in Silver for outcomes. (incompletely stated as well) For example:
    >Launch: "May be limited in scope to new products, apps, websites."
    
    - This might be better stated as, "Accessibility efforts in the development process limited to new products, apps, and websites, or starting to assess/address a small number of existing high priority ICT.
- The outcomes don't fully cover the situations that would be occur at that level of maturity. For example:
    >Inactive: "If ACRs/VPATs are required, they are not being produced."
    
    - IMO, ACRs aren't the only poor outcome if inactive. I would think that none of the organization-developed ICT would be accessible would be an outcome at this stage. They may also be receiving customer complaints or requests for accessible products that they are unable to address.

**Comment by Helixopp** [comment]
The Maturity Model is technology and standard agnostic. See section 2.3. If you have specific edits to suggest please provide a PR.

**Comment by swinehartganderson** [comment]
This issue should be addressed in the most recent publication update. We hope you’ll review the updated information and continue providing feedback by filing Github issues.
