### ISSUE TITLE
Change "are accessible" to  "are more accessible" in Abstract

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#93]
https://w3c.github.io/maturity-model/

The first sentence makes a statement that the model can be used to produce products that **'are'** accessible.
This completely depends on the user (and thus is not always a fact) and so to place this kind of text in more realistic perspective, and after multiple conversation, WCAG as an example adds the word **'more'** to a sentence like that.

My proposal is to do the same

Change:
> Abstract
> The W3C Accessibility Maturity Model is a guide for organizations to evaluate and improve their business processes to produce digital products that are accessible to people with disabilities.

To:
> Abstract
> The W3C Accessibility Maturity Model is a guide for organizations to evaluate and improve their business processes to produce digital products that are **more** accessible to people with disabilities.

**Comment by maryjom** [comment]
Agree that "more" makes this a more accurate statement. As an aside, I don't think it's JUST about producing more accessible digital products, it's about elevating an organization's awareness, sensitivity, and actions to support the development and use of accessible technology. It's broader than products, as it covers procurement, support, etc.

**Comment by Helixopp** [comment]
A new draft has been published. If you still have editorial recommendations please open a new issue.
