### ISSUE TITLE
rephrase sentence to make clear it is not about an "organization in accessibility practices"

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#94]
https://w3c.github.io/maturity-model/#About-maturity-model

Rephrase sentence so it can not be read in two ways...
Second bullet can be read as referring to "an organization in accessibility practices" while it is "effectiveness of accessibility practices"

1.1 About the W3C Accessibility Maturity Model

second bullet:

Change:
> - helps with the assessment of the current effectiveness of a person, group, or an organization in accessibility practices

To:
> - helps with the assessment of the current effectiveness in accessibility practices of a person, group, or an organization

**Comment by Helixopp** [comment]
A new draft has been published. If you still have editorial recommendations please open a new issue.
