### ISSUE TITLE
Assumption made that products are produced accessible, needs small adjustment

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#95]
https://w3c.github.io/maturity-model/#About-maturity-model

An assumption is made that organizations produce accessible products, this should be adjusted

About the W3C Accessibility Maturity Model

Change:
> However, these metrics don’t indicate how the organization is doing operationally to continue to produce accessible products without examining some key corporate processes.

To option 1: (add start with)
> However, these metrics don’t indicate how the organization is doing operationally **to start with or continue** to produce accessible products without examining some key corporate processes.

Or to option 2: (delete continue)
> However, these metrics don’t indicate how the organization is doing operationally to produce accessible products without examining some key corporate processes.

**Comment by jake-abma** [comment]
(ps. also here **'more accessible products'** is the better way to expres what we mean. Saying 'accessible products' will raise lots of voices asking "accessible to whom?")

**Comment by Helixopp** [comment]
Thank you for your suggestion, we agree with your option 2
