### ISSUE TITLE
Which Methodology is the model referring to?

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#96]
https://w3c.github.io/maturity-model/#About-maturity-model

In the following sentence a statement is made that the W3C AMM is part of a **bigger** methodology (?!) but is does not explain / refer to which one. We need to link to this methodology, or if it does not really exist change what we mean to say here. 

> The W3C Accessibility ​Maturity Model is a big part of a “shift-left” methodology of preventing problems from recurring, not fixing them after they have happened.

Also it's not only about 'recurring' but also 'occurring', a tweak here is also needed...

**Comment by Helixopp** [comment]
This section has been revised. Please review the latest draft. Please file a new issue if you still do not agree with the verbiage
