### ISSUE TITLE
'Stages' or 'levels'?

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#98]
https://w3c.github.io/maturity-model/#About-maturity-model

Sometimes we talk about **Levels**, other times about **Stages**, this needs to be consistent. (I was searching for one, could't find, turned out to be a different word in other places...)

https://w3c.github.io/maturity-model/#About-maturity-model

> Most maturity models contain a number of levels with increasing levels of maturity. Each level contains a definition, controls, a list of processes, and [proof points](https://w3c.github.io/maturity-model/#dfn-proof-point) that can be produced for an organization to legitimately claim that they are at a particular level of maturity.

https://w3c.github.io/maturity-model/#description-maturity-stages

> 2.3 Maturity Stages
> Each stage is attained by meeting the defined outcomes for that specific [dimension](https://w3c.github.io/maturity-model/#dfn-dimension). The completed [proof points](https://w3c.github.io/maturity-model/#dfn-proof-point) demonstrate the efforts to achieve the outcomes for a [maturity stage](https://w3c.github.io/maturity-model/#dfn-maturity-stage).

**Comment by Helixopp** [comment]
I did find both terms used throughout the document. We will review and see if they are interchangeable, but decide on one to use instead of both
