### ISSUE TITLE
"Outcomes" missing in sentence while we build on this term

### ISSUE THREAD

**Issue by jake-abma** [w3c/maturity-model#99]
https://w3c.github.io/maturity-model/#About-maturity-model

In the following sentence we talk about **'controls'** and **', a list of processes'** and I don't find these back in the document.
The term **"outcomes"** we use and build upon is lacking here... we should align this

> ​Most maturity models contain a number of levels with increasing levels of maturity. Each level contains a definition, controls, a list of processes, and [proof points](https://w3c.github.io/maturity-model/#dfn-proof-point) that can be produced for an organization to legitimately claim that they are at a particular level of maturity.

**Comment by Helixopp** [comment]
We believe the latest working draft addresses your concerns in this issue. If they still persist please reopen the issue or file a new one
